/* static.c - autogenerated by makefile */
#include <re_types.h>
#include <re_mod.h>

extern const struct mod_export exports_wincons;
extern const struct mod_export exports_stun;
extern const struct mod_export exports_turn;
extern const struct mod_export exports_ice;
extern const struct mod_export exports_natbd;
extern const struct mod_export exports_auloop;
extern const struct mod_export exports_presence;
extern const struct mod_export exports_menu;
extern const struct mod_export exports_contact;
extern const struct mod_export exports_vumeter;
extern const struct mod_export exports_mwi;
extern const struct mod_export exports_account;
extern const struct mod_export exports_natpmp;
extern const struct mod_export exports_httpd;
extern const struct mod_export exports_srtp;
extern const struct mod_export exports_uuid;
extern const struct mod_export exports_debug_cmd;
extern const struct mod_export exports_ctrl_tcp;
extern const struct mod_export exports_b2bua;
extern const struct mod_export exports_avcodec;
extern const struct mod_export exports_vp8;
extern const struct mod_export exports_vp9;
extern const struct mod_export exports_avformat;
extern const struct mod_export exports_sdl2;
extern const struct mod_export exports_vidloop;
extern const struct mod_export exports_selfview;
extern const struct mod_export exports_vidbridge;
extern const struct mod_export exports_fakevideo;
extern const struct mod_export exports_cons;
extern const struct mod_export exports_g711;
extern const struct mod_export exports_l16;
extern const struct mod_export exports_winwave;

const struct mod_export *mod_table[] = {
  &exports_wincons,
  &exports_stun,
  &exports_turn,
  &exports_ice,
  &exports_natbd,
  &exports_auloop,
  &exports_presence,
  &exports_menu,
  &exports_contact,
  &exports_vumeter,
  &exports_mwi,
  &exports_account,
  &exports_natpmp,
  &exports_httpd,
  &exports_srtp,
  &exports_uuid,
  &exports_debug_cmd,
  &exports_ctrl_tcp,
  &exports_b2bua,
  &exports_avcodec,
  &exports_vp8,
  &exports_vp9,
  &exports_avformat,
  &exports_sdl2,
  &exports_vidloop,
  &exports_selfview,
  &exports_vidbridge,
  &exports_fakevideo,
  &exports_cons,
  &exports_g711,
  &exports_l16,
  &exports_winwave,
  NULL
};
